/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import Service.Service; // pastikan ini sesuai package kamu

/**
 *
 * @author VOIR
 */
public class AdminEditKelurahan extends javax.swing.JFrame {

    private final Service service = new Service();
    private double latitude = 0.0;
    private double longitude = 0.0;

    public AdminEditKelurahan() {
        initComponents();
        setLocationRelativeTo(null);
        tampilkanDataKelurahan();

        // Klik baris tabel -> isi field
        tblKelurahan.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && tblKelurahan.getSelectedRow() != -1) {
                isiFieldDariTabel();
            }
        });
    }

    // Menampilkan data kelurahan
    private void tampilkanDataKelurahan() {
        try (Connection conn = service.getConnection()) {
            String sql = "SELECT * FROM kelurahan ORDER BY id_kelurahan ASC";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            DefaultTableModel model = new DefaultTableModel(
                new Object[]{"ID", "Nama", "Lokasi", "Zona", "Latitude", "Longitude"}, 0
            );

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_kelurahan"),
                    rs.getString("nama_kelurahan"),
                    rs.getString("lokasi_kelurahan"),
                    rs.getString("zona"),
                    rs.getDouble("latitude"),
                    rs.getDouble("longitude")
                });
            }

            tblKelurahan.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + e.getMessage());
        }
    }

    // Mengosongkan field input
    private void kosongkanField() {
        txtNama.setText("");
        txtLokasiKelurahan.setText("");
        comboZona.setSelectedIndex(0);
        latitude = 0.0;
        longitude = 0.0;
    }

    // Isi field saat klik tabel
    private void isiFieldDariTabel() {
        int baris = tblKelurahan.getSelectedRow();
        if (baris >= 0) {
            txtNama.setText(tblKelurahan.getValueAt(baris, 1).toString());
            txtLokasiKelurahan.setText(tblKelurahan.getValueAt(baris, 2).toString());
            comboZona.setSelectedItem(tblKelurahan.getValueAt(baris, 3).toString());
            latitude = Double.parseDouble(tblKelurahan.getValueAt(baris, 4).toString());
            longitude = Double.parseDouble(tblKelurahan.getValueAt(baris, 5).toString());
        }
    }

    // Setter untuk koordinat dari Map
    public void setSelectedCoordinates(double lat, double lon) {
        this.latitude = lat;
        this.longitude = lon;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TambahKelurahanButton = new javax.swing.JButton();
        txtLokasiKelurahan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnKembali = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        comboZona = new javax.swing.JComboBox<>();
        pilihLokasi1 = new javax.swing.JButton();
        txtNama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        HapusKelurahanButton = new javax.swing.JButton();
        EditFKelurahanButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKelurahan = new javax.swing.JTable();
        lihatDetail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(830, 520));
        setPreferredSize(new java.awt.Dimension(830, 520));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        TambahKelurahanButton.setBackground(new java.awt.Color(204, 255, 204));
        TambahKelurahanButton.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        TambahKelurahanButton.setText("Tambah Kelurahan");
        TambahKelurahanButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TambahKelurahanButton.setFocusPainted(false);
        TambahKelurahanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahKelurahanButtonActionPerformed(evt);
            }
        });
        jPanel1.add(TambahKelurahanButton);
        TambahKelurahanButton.setBounds(200, 140, 140, 29);

        txtLokasiKelurahan.setBackground(new java.awt.Color(230, 230, 230));
        txtLokasiKelurahan.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        txtLokasiKelurahan.setBorder(null);
        txtLokasiKelurahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLokasiKelurahanActionPerformed(evt);
            }
        });
        jPanel1.add(txtLokasiKelurahan);
        txtLokasiKelurahan.setBounds(330, 90, 180, 29);

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/emoticon.png"))); // NOI18N
        jLabel1.setText("Zona");
        jLabel1.setIconTextGap(8);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(530, 70, 80, 19);

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/map.png"))); // NOI18N
        jLabel3.setText("Lokasi Kelurahan");
        jLabel3.setIconTextGap(8);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(330, 70, 140, 19);

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 50, 820, 20);

        btnKembali.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/left-arrow.png"))); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.setBorderPainted(false);
        btnKembali.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnKembali.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKembali.setIconTextGap(8);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali);
        btnKembali.setBounds(0, 10, 120, 30);

        jLabel5.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Menambahkan & Mengedit Kelurahan");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(570, 10, 240, 30);

        comboZona.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        comboZona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "merah", "kuning", "hijau" }));
        comboZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboZonaActionPerformed(evt);
            }
        });
        jPanel1.add(comboZona);
        comboZona.setBounds(530, 90, 190, 30);

        pilihLokasi1.setBackground(new java.awt.Color(204, 204, 255));
        pilihLokasi1.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        pilihLokasi1.setText("Pilih Koordinat");
        pilihLokasi1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pilihLokasi1.setFocusPainted(false);
        pilihLokasi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihLokasi1ActionPerformed(evt);
            }
        });
        jPanel1.add(pilihLokasi1);
        pilihLokasi1.setBounds(70, 140, 120, 29);

        txtNama.setBackground(new java.awt.Color(230, 230, 230));
        txtNama.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        txtNama.setBorder(null);
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNama);
        txtNama.setBounds(130, 90, 180, 29);

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/tag.png"))); // NOI18N
        jLabel6.setText("Nama Kelurahan");
        jLabel6.setIconTextGap(8);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(130, 70, 120, 19);

        HapusKelurahanButton.setBackground(new java.awt.Color(255, 102, 102));
        HapusKelurahanButton.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        HapusKelurahanButton.setText("Hapus Kelurahan");
        HapusKelurahanButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        HapusKelurahanButton.setFocusPainted(false);
        HapusKelurahanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusKelurahanButtonActionPerformed(evt);
            }
        });
        jPanel1.add(HapusKelurahanButton);
        HapusKelurahanButton.setBounds(490, 140, 120, 29);

        EditFKelurahanButton.setBackground(new java.awt.Color(51, 153, 255));
        EditFKelurahanButton.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        EditFKelurahanButton.setText("Perbarui Kelurahan");
        EditFKelurahanButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EditFKelurahanButton.setFocusPainted(false);
        EditFKelurahanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditFKelurahanButtonActionPerformed(evt);
            }
        });
        jPanel1.add(EditFKelurahanButton);
        EditFKelurahanButton.setBounds(350, 140, 130, 29);

        tblKelurahan.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        tblKelurahan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Lokasi", "Zona", "Lotitude", "Longitude"
            }
        ));
        tblKelurahan.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(tblKelurahan);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 190, 820, 280);

        lihatDetail.setBackground(new java.awt.Color(255, 255, 153));
        lihatDetail.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lihatDetail.setText("Lihat detail");
        lihatDetail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lihatDetail.setFocusPainted(false);
        lihatDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatDetailActionPerformed(evt);
            }
        });
        jPanel1.add(lihatDetail);
        lihatDetail.setBounds(620, 140, 120, 29);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 820, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLokasiKelurahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLokasiKelurahanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLokasiKelurahanActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        this.dispose(); // menutup halaman LoginMenu
        new AdminHomeMenu().setVisible(true); // membuka halaman LoginUser
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void comboZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboZonaActionPerformed

    }//GEN-LAST:event_comboZonaActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void lihatDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatDetailActionPerformed
        int baris = tblKelurahan.getSelectedRow();
        if (baris < 0) {
            JOptionPane.showMessageDialog(this, "Pilih kelurahan terlebih dahulu!");
            return;
        }

        StringBuilder detail = new StringBuilder();
        detail.append("Nama Kelurahan: ").append(tblKelurahan.getValueAt(baris, 1)).append("\n");
        detail.append("Lokasi: ").append(tblKelurahan.getValueAt(baris, 2)).append("\n");
        detail.append("Zona: ").append(tblKelurahan.getValueAt(baris, 3)).append("\n");
        detail.append("Latitude: ").append(tblKelurahan.getValueAt(baris, 4)).append("\n");
        detail.append("Longitude: ").append(tblKelurahan.getValueAt(baris, 5)).append("\n");

        JTextArea area = new JTextArea(detail.toString());
        area.setEditable(false);
        area.setFont(new java.awt.Font("Poppins", java.awt.Font.BOLD, 12));
        area.setLineWrap(true);
        area.setWrapStyleWord(true);
        JScrollPane scroll = new JScrollPane(area);
        scroll.setPreferredSize(new java.awt.Dimension(400, 250));

        JOptionPane.showMessageDialog(this, scroll, "Detail Kelurahan", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_lihatDetailActionPerformed

    private void EditFKelurahanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditFKelurahanButtonActionPerformed
        int baris = tblKelurahan.getSelectedRow();
        if (baris < 0) {
            JOptionPane.showMessageDialog(this, "Pilih kelurahan yang akan diperbarui!");
            return;
        }

        int id = Integer.parseInt(tblKelurahan.getValueAt(baris, 0).toString());
        String nama = txtNama.getText().trim();
        String lokasi = txtLokasiKelurahan.getText().trim();
        String zona = comboZona.getSelectedItem().toString();

        try (Connection conn = service.getConnection()) {
            PreparedStatement ps = conn.prepareStatement(
                "UPDATE kelurahan SET nama_kelurahan=?, lokasi_kelurahan=?, zona=?, latitude=?, longitude=? WHERE id_kelurahan=?");
            ps.setString(1, nama);
            ps.setString(2, lokasi);
            ps.setString(3, zona);
            ps.setDouble(4, latitude);
            ps.setDouble(5, longitude);
            ps.setInt(6, id);
            ps.executeUpdate();

            tampilkanDataKelurahan();
            kosongkanField();
            JOptionPane.showMessageDialog(this, "Data kelurahan berhasil diperbarui!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Kesalahan: " + e.getMessage());
        }
    }

    private void hapusKelurahan() {
        int baris = tblKelurahan.getSelectedRow();
        if (baris < 0) {
            JOptionPane.showMessageDialog(this, "Pilih kelurahan yang akan dihapus!");
            return;
        }

        int id = Integer.parseInt(tblKelurahan.getValueAt(baris, 0).toString());
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus kelurahan ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            try (Connection conn = service.getConnection()) {
                PreparedStatement ps = conn.prepareStatement("DELETE FROM kelurahan WHERE id_kelurahan=?");
                ps.setInt(1, id);
                ps.executeUpdate();

                tampilkanDataKelurahan();
                kosongkanField();
                JOptionPane.showMessageDialog(this, "Kelurahan berhasil dihapus!");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Kesalahan: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_EditFKelurahanButtonActionPerformed

    private void HapusKelurahanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusKelurahanButtonActionPerformed
        int baris = tblKelurahan.getSelectedRow();
        if (baris < 0) {
            JOptionPane.showMessageDialog(this, "Pilih kelurahan yang akan dihapus!");
            return;
        }

        int id = Integer.parseInt(tblKelurahan.getValueAt(baris, 0).toString());
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus kelurahan ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            try (Connection conn = service.getConnection()) {
                PreparedStatement ps = conn.prepareStatement("DELETE FROM kelurahan WHERE id_kelurahan=?");
                ps.setInt(1, id);
                ps.executeUpdate();

                tampilkanDataKelurahan();
                kosongkanField();
                JOptionPane.showMessageDialog(this, "Kelurahan berhasil dihapus!");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Kesalahan: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_HapusKelurahanButtonActionPerformed

    private void TambahKelurahanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahKelurahanButtonActionPerformed
        String nama = txtNama.getText().trim();
        String lokasi = txtLokasiKelurahan.getText().trim();
        String zona = comboZona.getSelectedItem().toString();

        if (nama.isEmpty() || lokasi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Isi semua kolom terlebih dahulu!");
            return;
        }

        try (Connection conn = service.getConnection()) {
            PreparedStatement ps = conn.prepareStatement(
                "INSERT INTO kelurahan (nama_kelurahan, lokasi_kelurahan, zona, latitude, longitude) VALUES (?, ?, ?, ?, ?)");
            ps.setString(1, nama);
            ps.setString(2, lokasi);
            ps.setString(3, zona);
            ps.setDouble(4, latitude);
            ps.setDouble(5, longitude);
            ps.executeUpdate();

            tampilkanDataKelurahan();
            kosongkanField();
            JOptionPane.showMessageDialog(this, "Kelurahan berhasil ditambahkan!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Kesalahan: " + e.getMessage());
        }
    }//GEN-LAST:event_TambahKelurahanButtonActionPerformed

    private void pilihLokasi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihLokasi1ActionPerformed
        Map map = new Map(this);
        map.setVisible(true);
    }//GEN-LAST:event_pilihLokasi1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            com.formdev.flatlaf.FlatLightLaf.setup();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(() -> new AdminEditKelurahan().setVisible(true));
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditFKelurahanButton;
    private javax.swing.JButton HapusKelurahanButton;
    private javax.swing.JButton TambahKelurahanButton;
    private javax.swing.JButton btnKembali;
    private javax.swing.JComboBox<String> comboZona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton lihatDetail;
    private javax.swing.JButton pilihLokasi1;
    private javax.swing.JTable tblKelurahan;
    private javax.swing.JTextField txtLokasiKelurahan;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
